---

- name: Configure hostname
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: Configure timezone
  community.general.timezone:
    name: America/New_York

- name: Create user
  ansible.builtin.user:
    append: true
    groups: sudo
    name: '{{ username }}'
    shell: /bin/bash

- name: Create sudo config for user
  ansible.builtin.template:
    dest: /etc/sudoers.d/{{ username }}
    group: root
    mode: "0400"
    owner: root
    src: sudo_user.j2

- name: Install dependencies
  ansible.builtin.apt:
    autoremove: true
    clean: true
    name: '{{ item }}'
    state: present
  with_items:
    - bind9-dnsutils
    - curl
    - ethtool
    - hdparm
    - htop
    - iftop
    - iotop
    - jq
    - lftp
    - lm-sensors
    - lshw
    - lsof
    - mtr
    - neovim
    - net-tools
    - netcat-traditional
    - nmap
    - openssh-client
    - openssh-server
    - pv
    - tcpdump
    - tmux
    - tree
    - unzip
    - wget
    - whois

- name: Create NeoVIM config directory
  ansible.builtin.file:
    path: /home/{{ username }}/.config/nvim
    owner: '{{ username }}'
    group: '{{ username }}'
    state: directory
    mode: "0755"

- name: Populate NeoVIM config
  ansible.builtin.template:
    src: nvim_init.j2
    dest: /home/{{ username }}/.config/nvim/init.vim
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: "0644"

- name: Install Vundle for NeoVIM
  ansible.builtin.git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: /home/{{ username }}/.vim/bundle/Vundle.vim
    clone: true
    update: false
  become: true
  become_user: "{{ username }}"
