---

- Name: Download latest K3s binary
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}%2Bk3s1/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: '0755'
