---

# Check is /var/lib/rancher/k3s/server/node-token exists
# IF NOT, manually run `k3s server` to bootstrap and then kill the process

- name: Get K3s token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token

- name: Set token var
  ansible.builtin.set_fact:
    k3s_node_token: "{{ k3s_token.content | b64decode | trim }}"

- name: Populate K3s unit file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644

- name: Enable and start K3s
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true
    daemon_reload: true